spring:
  application:
    name: boot3-api

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:mem:testdb

  jpa:
    show-sql: true
#    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create
