spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    context-path: /api/v1


rland:
  jwt:
    secret: "YSlaqDrGCSE6qtZx1J5MKksWHQjqOLUHg41vRtwCHEi3+duomrV/XAReIJJH3vW0gQ00PEZkF+hDCToQpmtMIw=="